PREFIX mko: <http://macedonian-kg.mk/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?label ?externalLink
WHERE {
  ?entity mko:externalLink ?externalLink .
  OPTIONAL { ?entity rdfs:label ?label }
}
ORDER BY ?entity ?externalLink
LIMIT 100
