#!/usr/bin/env python3
"""
Validate and clean the Macedonian History KG Turtle output.

Default use:
    .venv\\Scripts\\python.exe 2. validate_clean.py --audit-only
    .venv\\Scripts\\python.exe 2. validate_clean.py

The script is tuned for the graph generated by 1. scrape.py:
    output/mk_history_full.ttl -> output/mk_history_clean.ttl
"""

from __future__ import annotations

import argparse
import logging
import re
from collections import Counter, defaultdict
from pathlib import Path

from rdflib import BNode, Dataset, Graph, Literal, Namespace, URIRef
from rdflib.namespace import OWL, RDF, RDFS, SKOS, XSD

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

MK = Namespace("http://macedonian-kg.mk/resource/")
MKO = Namespace("http://macedonian-kg.mk/ontology#")
WD = Namespace("http://www.wikidata.org/entity/")
TIME = Namespace("http://www.w3.org/2006/time#")
GEO = Namespace("http://www.opengis.net/ont/geosparql#")

DATE_PREDICATES = {
    MKO.birthDate,
    MKO.deathDate,
    MKO.startDate,
    MKO.endDate,
    MKO.foundingDate,
    MKO.dissolutionDate,
    MKO.dateCreated,
    TIME.hasBeginning,
    TIME.hasEnd,
}

EXPECTED_CLASSES = {
    MKO.Person,
    MKO.HistoricalEvent,
    MKO.Place,
    MKO.Organization,
    MKO.HistoricalDocument,
    MKO.Period,
}

VALID_LANGS = {"mk", "en", "bg", "tr", "sr", "el", "sq", ""}
DATE_RE = re.compile(r"^-?\d{1,6}(-\d{2}(-\d{2})?)?$")
QID_LABEL_RE = re.compile(r"^Q\d+$")
MOJIBAKE_RE = re.compile(r"[ÐÑÂâ][\x80-\uffff]?|Ã.")
WIKIDATA_GENID_RE = re.compile(r"^https?://www\.wikidata\.org/\.well-known/genid/")


def rdf_format(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix in {".ttl", ".turtle"}:
        return "turtle"
    if suffix == ".nq":
        return "nquads"
    if suffix == ".trig":
        return "trig"
    return "nt"


def load(path: Path) -> Graph:
    fmt = rdf_format(path)
    graph = Dataset(default_union=True) if fmt in {"nquads", "trig"} else Graph()
    graph.parse(str(path), format=fmt)
    log.info("Loaded %s triples from %s", f"{len(graph):,}", path)
    return graph


def qname(graph: Graph, node) -> str:
    try:
        return graph.namespace_manager.normalizeUri(node)
    except Exception:
        return str(node)


def is_date_like(value: str) -> bool:
    value = value.strip()
    if value.startswith("+"):
        value = value[1:]
    if "T" in value:
        value = value.split("T", 1)[0]
    return bool(DATE_RE.match(value))


def normalize_date_literal(value: str) -> Literal | None:
    raw = value.strip()
    if not raw or WIKIDATA_GENID_RE.match(raw):
        return None

    if raw.startswith("+"):
        raw = raw[1:]
    if "T" in raw:
        raw = raw.split("T", 1)[0]
    raw = raw.rstrip("Zz")

    if not DATE_RE.match(raw):
        return None

    parts = raw.split("-")
    try:
        if len(parts) == 1:
            year = int(parts[0])
            return Literal(f"{year:04d}", datatype=XSD.gYear)
        if len(parts) == 2:
            year = int(parts[0])
            month = int(parts[1])
            if month == 0:
                return Literal(f"{year:04d}", datatype=XSD.gYear)
            return Literal(f"{year:04d}-{month:02d}", datatype=XSD.gYearMonth)
        if len(parts) == 3:
            year = int(parts[0])
            month = int(parts[1])
            day = int(parts[2])
            if month == 0 and day == 0:
                return Literal(f"{year:04d}", datatype=XSD.gYear)
            if day == 0:
                return Literal(f"{year:04d}-{month:02d}", datatype=XSD.gYearMonth)
            return Literal(f"{year:04d}-{month:02d}-{day:02d}", datatype=XSD.date)
    except ValueError:
        return None

    return None


def looks_mojibake(text: str) -> bool:
    return bool(MOJIBAKE_RE.search(text))


def repair_mojibake(text: str) -> str:
    if not looks_mojibake(text):
        return text

    for encoding in ("cp1252", "latin1"):
        try:
            repaired = text.encode(encoding).decode("utf-8")
        except UnicodeError:
            continue
        if repaired != text and not looks_mojibake(repaired):
            return repaired
    return text


def audit(graph: Graph) -> dict:
    issues = {
        "blank_subjects": [],
        "uri_subjects_without_type": [],
        "unexpected_classes": [],
        "missing_labels": [],
        "qid_labels": [],
        "duplicate_labels": [],
        "bad_lang_tags": [],
        "empty_literals": [],
        "mojibake_literals": [],
        "date_predicate_non_dates": [],
        "bad_date_literals": [],
        "wikidata_genid_date_literals": [],
        "sameas_non_wikidata": [],
    }

    for subject in set(graph.subjects()):
        if isinstance(subject, BNode):
            issues["blank_subjects"].append(str(subject))
            continue

        if not isinstance(subject, URIRef):
            continue

        types = list(graph.objects(subject, RDF.type))
        if not types:
            issues["uri_subjects_without_type"].append(str(subject))
        if any(t in EXPECTED_CLASSES for t in types):
            if not list(graph.objects(subject, RDFS.label)):
                issues["missing_labels"].append(str(subject))
        for rdf_type in types:
            if str(rdf_type).startswith(str(MKO)) and rdf_type not in EXPECTED_CLASSES:
                issues["unexpected_classes"].append((str(subject), str(rdf_type)))

    label_map = defaultdict(lambda: defaultdict(list))
    for subject, predicate, obj in graph.triples((None, None, None)):
        if predicate in (RDFS.label, SKOS.prefLabel) and isinstance(obj, Literal):
            label_map[str(subject)][obj.language or ""].append(str(obj))
            if QID_LABEL_RE.match(str(obj)):
                issues["qid_labels"].append((str(subject), str(obj)))

        if predicate == OWL.sameAs and not str(obj).startswith(str(WD)):
            issues["sameas_non_wikidata"].append((str(subject), str(obj)))

        if not isinstance(obj, Literal):
            continue

        text = str(obj)
        if text.strip() == "":
            issues["empty_literals"].append((str(subject), str(predicate)))
        if obj.language and obj.language.lower() not in VALID_LANGS:
            issues["bad_lang_tags"].append((str(subject), text, obj.language))
        if looks_mojibake(text):
            issues["mojibake_literals"].append((str(subject), str(predicate), text))

        if predicate in DATE_PREDICATES:
            if WIKIDATA_GENID_RE.match(text):
                issues["wikidata_genid_date_literals"].append((str(subject), str(predicate), text))
            elif not normalize_date_literal(text):
                issues["date_predicate_non_dates"].append((str(subject), str(predicate), text))
        elif obj.datatype in {XSD.date, XSD.gYear, XSD.gYearMonth} and not is_date_like(text):
            issues["bad_date_literals"].append((str(subject), str(predicate), text))

    for subject, labels_by_lang in label_map.items():
        for lang, labels in labels_by_lang.items():
            unique_labels = sorted(set(labels))
            if len(unique_labels) > 1:
                issues["duplicate_labels"].append((subject, lang, unique_labels))

    return issues


def print_report(graph: Graph, issues: dict) -> None:
    width = 72
    print("\n" + "=" * width)
    print("AUDIT REPORT")
    print("=" * width)
    print(f"Triples:           {len(graph):>8,}")
    print(f"Unique subjects:   {len(set(graph.subjects())):>8,}")
    print(f"Unique predicates: {len(set(graph.predicates())):>8,}")
    print(f"Unique objects:    {len(set(graph.objects())):>8,}")

    print("\nClass counts:")
    class_counts = Counter(graph.objects(None, RDF.type))
    for rdf_type, count in class_counts.most_common():
        print(f"  {count:>5,}  {qname(graph, rdf_type)}")

    print("\nTop predicates:")
    pred_counts = Counter(graph.predicates())
    for predicate, count in pred_counts.most_common(15):
        print(f"  {count:>5,}  {qname(graph, predicate)}")

    print("\nIssues:")
    for key, values in issues.items():
        print(f"  {key:<32} {len(values):>6,}")

    samples = [
        ("wikidata_genid_date_literals", "Wikidata genid values used as dates"),
        ("date_predicate_non_dates", "Non-date values on date predicates"),
        ("mojibake_literals", "Mojibake text"),
        ("missing_labels", "Entities without labels"),
        ("qid_labels", "Labels that are only QIDs"),
    ]
    for key, title in samples:
        if not issues[key]:
            continue
        print(f"\n{title} (first 8):")
        for item in issues[key][:8]:
            print(f"  {item}")

    print("=" * width + "\n")


def clean(graph: Graph, *, fix_mojibake: bool = True) -> Graph:
    out = Graph()
    for prefix, namespace in graph.namespaces():
        out.bind(prefix, namespace)
    out.bind("mk", MK)
    out.bind("mko", MKO)
    out.bind("wd", WD)
    out.bind("time", TIME)
    out.bind("geo", GEO)

    removed = 0
    fixed = 0
    seen = set()

    for subject, predicate, obj in graph.triples((None, None, None)):
        if isinstance(obj, Literal) and str(obj).strip() == "":
            removed += 1
            continue

        if predicate in DATE_PREDICATES and isinstance(obj, Literal):
            normalized = normalize_date_literal(str(obj))
            if normalized is None:
                removed += 1
                continue
            if normalized != obj:
                obj = normalized
                fixed += 1

        if isinstance(obj, Literal) and fix_mojibake:
            repaired = repair_mojibake(str(obj))
            if repaired != str(obj):
                if obj.language:
                    obj = Literal(repaired, lang=obj.language.lower().split("-")[0])
                else:
                    obj = Literal(repaired, datatype=obj.datatype)
                fixed += 1
            elif obj.language and obj.language != obj.language.lower().split("-")[0]:
                obj = Literal(str(obj), lang=obj.language.lower().split("-")[0])
                fixed += 1

        key = (subject, predicate, obj)
        if key in seen:
            removed += 1
            continue
        seen.add(key)
        out.add((subject, predicate, obj))

    log.info("Cleaning: %s triples removed, %s literals normalized", removed, fixed)
    return out


SHACL_SHAPES = """
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix mko:  <http://macedonian-kg.mk/ontology#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .

mko:PersonShape a sh:NodeShape ;
    sh:targetClass mko:Person ;
    sh:property [
        sh:path rdfs:label ;
        sh:minCount 1 ;
        sh:message "Every person should have at least one rdfs:label."
    ] ;
    sh:property [
        sh:path owl:sameAs ;
        sh:minCount 1 ;
        sh:message "Every person should link back to Wikidata with owl:sameAs."
    ] .

mko:EventShape a sh:NodeShape ;
    sh:targetClass mko:HistoricalEvent ;
    sh:property [
        sh:path owl:sameAs ;
        sh:minCount 1 ;
        sh:message "Every event should link back to Wikidata with owl:sameAs."
    ] .

mko:PlaceShape a sh:NodeShape ;
    sh:targetClass mko:Place ;
    sh:property [
        sh:path rdfs:label ;
        sh:minCount 1 ;
        sh:message "Every place should have a label."
    ] .
"""


def validate_shacl(data_graph: Graph) -> bool:
    try:
        from pyshacl import validate
    except ImportError:
        log.warning("pyshacl is not installed; skipping SHACL validation")
        return True

    shapes = Graph().parse(data=SHACL_SHAPES, format="turtle")
    conforms, _, report_text = validate(data_graph, shacl_graph=shapes, inference="rdfs")
    if conforms:
        log.info("SHACL validation: conforms")
    else:
        log.warning("SHACL validation violations:\n%s", report_text)
    return bool(conforms)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="../output/mk_history_full.ttl")
    parser.add_argument("--output", default="../output/mk_history_clean.ttl")
    parser.add_argument("--audit-only", action="store_true")
    parser.add_argument("--no-fix-mojibake", action="store_true")
    parser.add_argument("--skip-shacl", action="store_true")
    args = parser.parse_args()

    graph = load(Path(args.input))
    before_issues = audit(graph)
    print_report(graph, before_issues)

    if args.audit_only:
        return

    cleaned = clean(graph, fix_mojibake=not args.no_fix_mojibake)
    after_issues = audit(cleaned)
    print_report(cleaned, after_issues)

    if not args.skip_shacl:
        validate_shacl(cleaned)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cleaned.serialize(destination=str(out_path), format="turtle")
    log.info("Saved %s clean triples to %s", f"{len(cleaned):,}", out_path)


if __name__ == "__main__":
    main()
